namespace TransportReservationSystem
{
    partial class FrmDrivers
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            panel1 = new Panel();
            Dashboard = new Label();
            label3 = new Label();
            label2 = new Label();
            AddDriverBtn = new Button();
            DriversGridView = new DataGridView();
            button1 = new Button();
            DeleteBtn = new Button();
            UpdateBtn = new Button();
            panel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)DriversGridView).BeginInit();
            SuspendLayout();
            // 
            // panel1
            // 
            panel1.BackColor = Color.AliceBlue;
            panel1.Controls.Add(Dashboard);
            panel1.Controls.Add(label3);
            panel1.Controls.Add(label2);
            panel1.Location = new Point(142, 60);
            panel1.Margin = new Padding(3, 4, 3, 4);
            panel1.Name = "panel1";
            panel1.Size = new Size(815, 176);
            panel1.TabIndex = 10;
            // 
            // Dashboard
            // 
            Dashboard.AutoSize = true;
            Dashboard.FlatStyle = FlatStyle.Flat;
            Dashboard.Font = new Font("Century Gothic", 27.75F, FontStyle.Bold, GraphicsUnit.Point, 0);
            Dashboard.ForeColor = SystemColors.ControlDark;
            Dashboard.Location = new Point(161, 35);
            Dashboard.Name = "Dashboard";
            Dashboard.Size = new Size(175, 56);
            Dashboard.TabIndex = 1;
            Dashboard.Text = "Drivers";
            Dashboard.TextAlign = ContentAlignment.MiddleCenter;
            // 
            // label3
            // 
            label3.AutoSize = true;
            label3.Font = new Font("Century Gothic", 14.25F, FontStyle.Bold, GraphicsUnit.Point, 0);
            label3.ForeColor = SystemColors.ControlDark;
            label3.Location = new Point(171, 109);
            label3.Name = "label3";
            label3.Size = new Size(266, 28);
            label3.TabIndex = 3;
            label3.Text = "Generated by Team 1";
            // 
            // label2
            // 
            label2.AutoSize = true;
            label2.Font = new Font("Century Gothic", 72F, FontStyle.Bold, GraphicsUnit.Point, 0);
            label2.ForeColor = Color.DarkViolet;
            label2.Location = new Point(3, 12);
            label2.Name = "label2";
            label2.Size = new Size(178, 141);
            label2.TabIndex = 2;
            label2.Text = "ITI";
            // 
            // AddDriverBtn
            // 
            AddDriverBtn.BackColor = Color.FromArgb(156, 39, 176);
            AddDriverBtn.Cursor = Cursors.Hand;
            AddDriverBtn.FlatAppearance.BorderColor = Color.FromArgb(192, 0, 192);
            AddDriverBtn.FlatAppearance.BorderSize = 0;
            AddDriverBtn.FlatAppearance.MouseDownBackColor = Color.FromArgb(156, 39, 160);
            AddDriverBtn.FlatAppearance.MouseOverBackColor = Color.FromArgb(156, 39, 170);
            AddDriverBtn.FlatStyle = FlatStyle.Flat;
            AddDriverBtn.Font = new Font("Segoe UI", 11.25F, FontStyle.Bold, GraphicsUnit.Point, 0);
            AddDriverBtn.ForeColor = Color.White;
            AddDriverBtn.Location = new Point(142, 259);
            AddDriverBtn.Margin = new Padding(3, 4, 3, 4);
            AddDriverBtn.Name = "AddDriverBtn";
            AddDriverBtn.Size = new Size(320, 57);
            AddDriverBtn.TabIndex = 34;
            AddDriverBtn.Text = "Add Driver";
            AddDriverBtn.UseVisualStyleBackColor = false;
            AddDriverBtn.Click += AddDriverBtn_Click;
            // 
            // DriversGridView
            // 
            DriversGridView.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            DriversGridView.Location = new Point(142, 356);
            DriversGridView.Name = "DriversGridView";
            DriversGridView.RowHeadersWidth = 51;
            DriversGridView.Size = new Size(915, 222);
            DriversGridView.TabIndex = 35;
            // 
            // button1
            // 
            button1.BackColor = Color.FromArgb(156, 39, 176);
            button1.Cursor = Cursors.Hand;
            button1.FlatAppearance.BorderColor = Color.FromArgb(192, 0, 192);
            button1.FlatAppearance.BorderSize = 0;
            button1.FlatAppearance.MouseDownBackColor = Color.FromArgb(156, 39, 160);
            button1.FlatAppearance.MouseOverBackColor = Color.FromArgb(156, 39, 170);
            button1.FlatStyle = FlatStyle.Flat;
            button1.Font = new Font("Segoe UI", 10F, FontStyle.Bold, GraphicsUnit.Point, 0);
            button1.ForeColor = Color.White;
            button1.Location = new Point(956, 600);
            button1.Margin = new Padding(3, 4, 3, 4);
            button1.Name = "button1";
            button1.Size = new Size(101, 36);
            button1.TabIndex = 36;
            button1.Text = "Refresh";
            button1.UseVisualStyleBackColor = false;
            button1.Click += button1_Click;
            // 
            // DeleteBtn
            // 
            DeleteBtn.BackColor = Color.FromArgb(156, 39, 176);
            DeleteBtn.Cursor = Cursors.Hand;
            DeleteBtn.FlatAppearance.BorderColor = Color.FromArgb(192, 0, 192);
            DeleteBtn.FlatAppearance.BorderSize = 0;
            DeleteBtn.FlatAppearance.MouseDownBackColor = Color.FromArgb(156, 39, 160);
            DeleteBtn.FlatAppearance.MouseOverBackColor = Color.FromArgb(156, 39, 170);
            DeleteBtn.FlatStyle = FlatStyle.Flat;
            DeleteBtn.Font = new Font("Segoe UI", 10F, FontStyle.Bold, GraphicsUnit.Point, 0);
            DeleteBtn.ForeColor = Color.White;
            DeleteBtn.Location = new Point(798, 600);
            DeleteBtn.Margin = new Padding(3, 4, 3, 4);
            DeleteBtn.Name = "DeleteBtn";
            DeleteBtn.Size = new Size(101, 36);
            DeleteBtn.TabIndex = 37;
            DeleteBtn.Text = "Delete";
            DeleteBtn.UseVisualStyleBackColor = false;
            DeleteBtn.Click += DeleteBtn_Click;
            // 
            // UpdateBtn
            // 
            UpdateBtn.BackColor = Color.FromArgb(156, 39, 176);
            UpdateBtn.Cursor = Cursors.Hand;
            UpdateBtn.FlatAppearance.BorderColor = Color.FromArgb(192, 0, 192);
            UpdateBtn.FlatAppearance.BorderSize = 0;
            UpdateBtn.FlatAppearance.MouseDownBackColor = Color.FromArgb(156, 39, 160);
            UpdateBtn.FlatAppearance.MouseOverBackColor = Color.FromArgb(156, 39, 170);
            UpdateBtn.FlatStyle = FlatStyle.Flat;
            UpdateBtn.Font = new Font("Segoe UI", 10F, FontStyle.Bold, GraphicsUnit.Point, 0);
            UpdateBtn.ForeColor = Color.White;
            UpdateBtn.Location = new Point(640, 600);
            UpdateBtn.Margin = new Padding(3, 4, 3, 4);
            UpdateBtn.Name = "UpdateBtn";
            UpdateBtn.Size = new Size(101, 36);
            UpdateBtn.TabIndex = 38;
            UpdateBtn.Text = "Update";
            UpdateBtn.UseVisualStyleBackColor = false;
            UpdateBtn.Click += UpdateBtn_Click;
            // 
            // FrmDrivers
            // 
            AutoScaleDimensions = new SizeF(8F, 20F);
            AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.AliceBlue;
            ClientSize = new Size(1097, 817);
            Controls.Add(UpdateBtn);
            Controls.Add(DeleteBtn);
            Controls.Add(button1);
            Controls.Add(DriversGridView);
            Controls.Add(AddDriverBtn);
            Controls.Add(panel1);
            Margin = new Padding(3, 4, 3, 4);
            Name = "FrmDrivers";
            Text = "FrmDrivers";
            Load += FrmDrivers_Load;
            panel1.ResumeLayout(false);
            panel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)DriversGridView).EndInit();
            ResumeLayout(false);
        }

        #endregion

        private Panel panel1;
        private Label Dashboard;
        private Label label3;
        private Label label2;
        private Button AddDriverBtn;
        private DataGridView DriversGridView;
        private Button button1;
        private Button DeleteBtn;
        private Button UpdateBtn;
    }
}